environment:
  matrix:
    - nodejs_version: STABLE
      configuration: publish
    - nodejs_version: LTS

install:
  - ps: Install-Product node $env:nodejs_version

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - npm install

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

test_script:
- cmd: npm run test:ci
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", `
                   (Resolve-Path C:\mocharesults.xml))
    [xml]$results = Get-Content C:\mocharesults.xml
    $failure = $results.SelectSingleNode("//failure")
    if ($failure -ne $null) 
    { 
        $host.SetShouldExit(1)
        Write-Host "Forcing build failure due to javascript unit test failure(s)"
    }

deploy_script:
  - ps: |
      if ($ENV:CONFIGURATION -eq "publish")
      {
        "//registry.npmjs.org/:_authToken=`$`{NPM_TOKEN`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
        iex "npm pack"
        iex "npm publish"
      }
    on:
      branch: master